### ISSUE TITLE
Write a guide on how to upload the firmware

### ISSUE THREAD

**Issue by hasenbanck** [hasenbanck/remram#7]
We support multiple ways on how to upload a firmware (DFU, Serial, SWD). We need to write a guide for all of them.

**Comment by G-Pereira** [comment]
I am looking to program it by hooking up a raspberry pi to the UART pins, can you explain how can I do that? I find odd not having to connect the STM32 reset pin to my RPi or the RTS signal.

**Comment by hasenbanck** [comment]
Simply flip the boot switch and hit the reset button. Then the bootloader will start and you can flash the board using the TX/RX pins and a tool such as stm32flash. Be sure to use the current git master, since the 0.5 version doesn't support the STM32F765VI.
